spring:
  application:
    name: ProfIs-backend
  datasource:
    url: jdbc:sqlite:profIs-database.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: classpath:/static/

   



